# Copyright (c) 2026 Shahid Ansari. All rights reserved.
# Proprietary software. Copying, modification, rebuilding or redistribution
# is not permitted without written permission. See LICENSE.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
