// Copyright (c) 2026 Shahid Ansari. All rights reserved.
// Proprietary software. Copying, modification, rebuilding or redistribution
// is not permitted without written permission. See LICENSE.
package com.whiplash.music.ui.onboarding

/**
 * Artwork shipped inside the app (assets/onboarding), so onboarding looks
 * finished on the first frame, on a slow connection, or with none at all.
 * Nothing here needs the network; live lookups only fill in artists that
 * aren't bundled (search results, a few names without a good photo).
 */
object OnboardingArt {
    private const val BASE = "file:///android_asset/onboarding"

    /** Welcome collage, sign-in fan (first three) and the blurred sign-in backdrop. */
    val covers: List<String> = listOf(
        "00_dua_lipa_future_nostalgia.webp",
        "01_anuv_jain_husn.webp",
        "02_bad_bunny_un_verano_sin_ti.webp",
        "03_the_weeknd_starboy.webp",
        "04_taylor_swift_midnights.webp",
        "05_tame_impala_currents.webp",
        "06_aashiqui_2.webp",
        "07_sza_sos.webp",
        "08_karan_aujla_making_memories.webp",
        "09_coldplay_music_of_the_spheres.webp",
        "10_olivia_rodrigo_sour.webp",
        "11_rockstar_a_r_rahman.webp",
        "12_ed_sheeran_divide.webp",
        "13_travis_scott_astroworld.webp",
        "14_the_weeknd_after_hours.webp",
    ).map { "$BASE/covers/$it" }

    /** Genre name → tile artwork. */
    val genres: Map<String, String> = mapOf(
        "Pop" to "pop.webp",
        "Hip-hop" to "hip_hop.webp",
        "Bollywood" to "bollywood.webp",
        "Romantic" to "romantic.webp",
        "Rock" to "rock.webp",
        "EDM" to "edm.webp",
        "Lo-fi" to "lo_fi.webp",
        "R&B" to "r_b.webp",
        "Indie" to "indie.webp",
        "Punjabi pop" to "punjabi_pop.webp",
        "K-pop" to "k_pop.webp",
        "Sufi" to "sufi.webp",
        "Party" to "party.webp",
        "Chill" to "chill.webp",
        "Jazz" to "jazz.webp",
        "Classical" to "classical.webp",
        "Metal" to "metal.webp",
        "Devotional" to "devotional.webp",
        "Workout" to "workout.webp",
        "Latin" to "latin.webp",
    ).mapValues { "$BASE/genres/${it.value}" }

    /** Suggested artist name → photo. */
    val artists: Map<String, String> = mapOf(
        "Taylor Swift" to "taylor_swift.webp",
        "The Weeknd" to "the_weeknd.webp",
        "Ed Sheeran" to "ed_sheeran.webp",
        "Coldplay" to "coldplay.webp",
        "Billie Eilish" to "billie_eilish.webp",
        "Dua Lipa" to "dua_lipa.webp",
        "Drake" to "drake.webp",
        "Imagine Dragons" to "imagine_dragons.webp",
        "Ariana Grande" to "ariana_grande.webp",
        "Bruno Mars" to "bruno_mars.webp",
        "Olivia Rodrigo" to "olivia_rodrigo.webp",
        "Post Malone" to "post_malone.webp",
        "Arijit Singh" to "arijit_singh.webp",
        "Shreya Ghoshal" to "shreya_ghoshal.webp",
        "Pritam" to "pritam.webp",
        "A. R. Rahman" to "a_r_rahman.webp",
        "Atif Aslam" to "atif_aslam.webp",
        "Jubin Nautiyal" to "jubin_nautiyal.webp",
        "Neha Kakkar" to "neha_kakkar.webp",
        "Armaan Malik" to "armaan_malik.webp",
        "Sonu Nigam" to "sonu_nigam.webp",
        "Badshah" to "badshah.webp",
        "Vishal-Shekhar" to "vishal_shekhar.webp",
        "KK" to "kk.webp",
        "Diljit Dosanjh" to "diljit_dosanjh.webp",
        "AP Dhillon" to "ap_dhillon.webp",
        "Karan Aujla" to "karan_aujla.webp",
        "Sidhu Moose Wala" to "sidhu_moose_wala.webp",
        "Guru Randhawa" to "guru_randhawa.webp",
        "Shubh" to "shubh.webp",
        "Anirudh Ravichander" to "anirudh_ravichander.webp",
        "Sid Sriram" to "sid_sriram.webp",
        "Yuvan Shankar Raja" to "yuvan_shankar_raja.webp",
        "Devi Sri Prasad" to "devi_sri_prasad.webp",
        "Anupam Roy" to "anupam_roy.webp",
        "Nachiketa" to "nachiketa.webp",
        "Shankar Mahadevan" to "shankar_mahadevan.webp",
        "Nusrat Fateh Ali Khan" to "nusrat_fateh_ali_khan.webp",
        "Ali Sethi" to "ali_sethi.webp",
        "Abida Parveen" to "abida_parveen.webp",
        "Bad Bunny" to "bad_bunny.webp",
        "Shakira" to "shakira.webp",
        "Karol G" to "karol_g.webp",
        "J Balvin" to "j_balvin.webp",
        "Rosalía" to "rosalia.webp",
        "BTS" to "bts.webp",
        "BLACKPINK" to "blackpink.webp",
        "NewJeans" to "newjeans.webp",
        "Stray Kids" to "stray_kids.webp",
        "TWICE" to "twice.webp",
        "YOASOBI" to "yoasobi.webp",
        "Kenshi Yonezu" to "kenshi_yonezu.webp",
        "Ado" to "ado.webp",
        "LiSA" to "lisa.webp",
        "Amr Diab" to "amr_diab.webp",
        "Nancy Ajram" to "nancy_ajram.webp",
        "Elissa" to "elissa.webp",
        "Stromae" to "stromae.webp",
        "Aya Nakamura" to "aya_nakamura.webp",
        "Indila" to "indila.webp",
        "Anitta" to "anitta.webp",
        "Marília Mendonça" to "marilia_mendonca.webp",
        "Jorge & Mateus" to "jorge_mateus.webp",
        "Eminem" to "eminem.webp",
        "Kendrick Lamar" to "kendrick_lamar.webp",
        "Travis Scott" to "travis_scott.webp",
        "Divine" to "divine.webp",
        "Linkin Park" to "linkin_park.webp",
        "Queen" to "queen.webp",
        "Arctic Monkeys" to "arctic_monkeys.webp",
        "Nirvana" to "nirvana.webp",
        "Alan Walker" to "alan_walker.webp",
        "Martin Garrix" to "martin_garrix.webp",
        "Avicii" to "avicii.webp",
        "Marshmello" to "marshmello.webp",
        "Lofi Girl" to "lofi_girl.webp",
        "Prateek Kuhad" to "prateek_kuhad.webp",
        "SZA" to "sza.webp",
        "Frank Ocean" to "frank_ocean.webp",
        "Lana Del Rey" to "lana_del_rey.webp",
        "The Local Train" to "the_local_train.webp",
        "Norah Jones" to "norah_jones.webp",
        "Frank Sinatra" to "frank_sinatra.webp",
        "Ludovico Einaudi" to "ludovico_einaudi.webp",
        "Hans Zimmer" to "hans_zimmer.webp",
        "Metallica" to "metallica.webp",
        "Bring Me The Horizon" to "bring_me_the_horizon.webp",
        "Hariharan" to "hariharan.webp",
        "Anuradha Paudwal" to "anuradha_paudwal.webp",
        "Harris Jayaraj" to "harris_jayaraj.webp",
        "S. Thaman" to "s_thaman.webp",
        "Ajay-Atul" to "ajay_atul.webp",
        "Avadhoot Gupte" to "avadhoot_gupte.webp",
        "Rahat Fateh Ali Khan" to "rahat_fateh_ali_khan.webp",
        "M. M. Keeravani" to "m_m_keeravani.webp",
    ).mapValues { "$BASE/artists/${it.value}" }
}
